### ISSUE TITLE
Error when import py8583spec

### ISSUE THREAD

**Issue by ducminhgd** [alxnik/py8583#4]
I got this error when import py8583spec `from py8583 import py8583spec`
```
    from py8583.py8583 import DT, LT, SpecError
ImportError: No module named py8583
```

**Comment by mzobe** [comment]
Managed to get it working fixing the references on line 76 of py8583.py i add 
**from py8583.py8583spec import ***
and on line 2 of py8583spec
from py8583.py8583 import DT ,LT


based on that i was able to run the host/client using the library

**Comment by oscarcp** [comment]
I'm having the same issue, it gets fixed by changing the imports.

**Comment by ducminhgd** [comment]
> I'm having the same issue, it gets fixed by changing the imports.

I forked and published as new module here https://pypi.org/project/ISO8583/, please take a look if it can help or not.
