### ISSUE TITLE
Message Header Not Included

### ISSUE THREAD

**Issue by anson2416** [alxnik/py8583#5]
hi, thanks for the implementation for ISO8583 with Python. In the sample, seesm nowhere to format the message header. 

any sample on IsoClient?

**Comment by alxnik** [comment]
Hi,
The library covers all the parts that are in the scope of ISO-8583 at this point. Can you please elaborate on what you mean by message header?

**Comment by cesc1802** [comment]
i think he say about TPDU

**Comment by jorgemprende** [comment]
Hello, thanks for the implementation for ISO8583 with Python. Can you help me with a client example? I need conect to a real server. Thanks so much!

**Comment by alxnik** [comment]
Hi,

The library doesn't cover TPDU or any other header as it is considered out of the scope of ISO8583. It should be relatively easy to implement though if you decide to do it.

A simple ISO client would be as follows:

```
req = py8583.Iso8583(IsoSpec = py8583spec.IsoSpec1987ASCII())

req.MTI('0800') # Set message MTI
req.Field(3, 1) # Enable Field 3
req.FieldData(fld, '000000') # Set field 3 data

req.DebugMessage()

send(req.BuildIso()) # Send message - replace with your own send
data = receive() # Receive reply - replace with your own receive

resp = py8583.Iso8583(data, IsoSpec = py8583spec.IsoSpec1987ASCII()) # Parse message

resp.DebugMessage()
```

**Comment by georgesystem** [comment]
Hi alxnik,

I am need send a optional header 4 bytes like the example show in this web 
https://nayibor.github.io/post/iso8583-message-structure/

Can you help me?

Thanks so much!

**Comment by alxnik** [comment]
Hi @georgesystem. As commented above, header is not in the scope of the library so I cannot help you out on that. It should not be too hard to implement though.
