### ISSUE TITLE
%s Value length larger than field maximum (6)

### ISSUE THREAD

**Issue by georgesystem** [alxnik/py8583#8]
Hello, what is wrong in my code? I need send this card data! Thanks!

`from config import *
import socket
from py8583 import * 

try:
	req = py8583.Iso8583(IsoSpec = py8583spec.IsoSpec1987ASCII())

	req.MTI('0200') # Set message MTI
	
	req.Field(2, 1) 
	req.FieldData(2, '5896580743857002') 
	
	req.Field(3, 1) 
	req.FieldData(3, '000000')
	
	req.Field(4, 1) 
	req.FieldData(4, '000000000000')
	
	req.Field(7, 1) 
	req.FieldData(7, '0612151557')
	
	req.Field(11, 1) 
	req.FieldData(11, '000001')
	
	req.Field(12, 1) 
	req.FieldData(12, '190612071557')
	
	req.Field(18, 1) 
	req.FieldData(18, '6011')
	
	req.Field(22, 1) 
	req.FieldData(22, '010011012110')
	
	req.Field(41, 1) 
	req.FieldData(41, '007899')
	
	req.Field(42, 1) 
	req.FieldData(42, 'TYME')
	
	req.Field(49, 1) 
	req.FieldData(49, '840')
	

	req.PrintMessage()

	# Send message - replace with your own send
	
	Socket = socket.socket()
	Socket.settimeout(socket_timeout)
	Socket.connect((socket_address, socket_port))
	Socket.send(req.BuildIso())
    
	# Receive reply - replace with your own receive
	data = Socket.recv(socket_recv_size)

	resp = py8583.Iso8583(data, IsoSpec = py8583spec.IsoSpec1987ASCII()) # Parse message

	resp.DebugMessage()
	
except socket.timeout:
    print("\33[41m La respuesta del host ha excedido el tiempo maximo")
except Exception as e:
    print("\33[41m Ha ocurrido un error: %s", e)`

**Comment by alxnik** [comment]
Hi,
At first glance I see no issue with what you have posted. What problem are you experiencing?

**Comment by georgesystem** [comment]
Hi,

I am getting this error:

%s Value length larger than field maximum (6)

Thanks!

**Comment by alxnik** [comment]
According to ISO 8583, field 12 has a maximum length of 6. You have entered 12, hence the exception
