### ISSUE TITLE
ValueError: Unknown format code 'd' for object of type 'str'

### ISSUE THREAD

**Issue by georgesystem** [alxnik/py8583#9]
Hello again, and sorry!

Im getting this error, i dont know if i am sending the data in wrong format ot its any else:

Thanks for help!

Traceback (most recent call last):
  File "request2.py", line 49, in <module>
    Socket.send(req.BuildIso())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\py8583\py8583.py", line 391, in BuildIso
    self.BuildField(field)
  **File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\py8583\py8583.py", line 341, in BuildField
    data = formatter.format(self.__FieldData[field])
ValueError: Unknown format code 'd' for object of type 'str'**

`from config import *
import socket
from py8583 import * 

#try:
req = py8583.Iso8583(IsoSpec = py8583spec.IsoSpec1987ASCII())

req.MTI('0200')

req.Field(2, 1) 
req.FieldData(2, '5896580743857002') 

req.Field(3, 1) 
req.FieldData(3, '000000')

req.Field(4, 1) 
req.FieldData(4, '000000000000')

req.Field(7, 1) 
req.FieldData(7, '0612151557')

req.Field(11, 1) 
req.FieldData(11, '000001')

req.Field(12, 1) 
req.FieldData(12, '190612')

req.Field(18, 1) 
req.FieldData(18, '6011')

req.Field(22, 1) 
req.FieldData(22, '010')

req.Field(41, 1) 
req.FieldData(41, '007899')

req.Field(42, 1) 
req.FieldData(42, 'TYME')

req.Field(49, 1) 
req.FieldData(49, '840')

req.PrintMessage()

Socket = socket.socket()
Socket.settimeout(socket_timeout)
Socket.connect((socket_address, socket_port))
Socket.send(req.BuildIso())

data = Socket.recv(socket_recv_size)

resp = py8583.Iso8583(data, IsoSpec = py8583spec.IsoSpec1987ASCII()) # Parse message

resp.DebugMessage()`

**Comment by alxnik** [comment]
Hi,

The field you are trying to fill is digit and you are trying to fill it
with a string. You should convert the string to int in order for it to work

**Comment by georgesystem** [comment]
Hi,

Thanks.

How i can print the frame before send?

Thanks!
